#!/bin/bash

# uhubctl Installation Script
# This script installs uhubctl from source and configures udev permissions
# 
# Usage: ./install_uhubctl.sh <version> <idVendor>
# Example: ./install_uhubctl.sh v2.6.0 2109
#
# Arguments:
#   version   - uhubctl version to install (e.g., v2.6.0, master)
#   idVendor  - USB vendor ID for udev permissions (e.g., 2109)

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to check if running as root
check_not_root() {
    if [ "$EUID" -eq 0 ]; then
        print_error "This script should not be run as root. Run as a regular user."
        exit 1
    fi
}

# Function to validate arguments
validate_arguments() {
    if [ $# -ne 2 ]; then
        print_error "Usage: $0 <version> <idVendor>"
        print_error "Example: $0 v2.6.0 2109"
        print_error ""
        print_error "Arguments:"
        print_error "  version   - uhubctl version to install (e.g., v2.6.0, master)"
        print_error "  idVendor  - USB vendor ID for udev permissions (e.g., 2109)"
        exit 1
    fi

    VERSION="$1"
    IDVENDOR="$2"

    # Validate idVendor format (should be hex, 4 characters)
    if ! [[ "$IDVENDOR" =~ ^[0-9a-fA-F]{4}$ ]]; then
        print_error "idVendor should be a 4-digit hexadecimal value (e.g., 2109, 05e3)"
        exit 1
    fi

    print_info "Installing uhubctl version: $VERSION"
    print_info "USB Vendor ID for permissions: $IDVENDOR"
}

# Function to install dependencies
install_dependencies() {
    print_info "Installing dependencies..."
    
    if command_exists apt-get; then
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev pkgconf git build-essential
    elif command_exists yum; then
        sudo yum install -y libusb1-devel pkgconf git gcc make
    elif command_exists zypper; then
        sudo zypper install -y libusb-1_0-devel pkgconf git gcc make
    else
        print_error "Unsupported package manager. Please install manually:"
        print_error "  - libusb-1.0-dev (Ubuntu) / libusb1-devel (RedHat) / libusb-1_0-devel (OpenSUSE)"
        print_error "  - pkgconf"
        print_error "  - git"
        print_error "  - build tools (gcc, make)"
        exit 1
    fi
    
    print_success "Dependencies installed"
}

# Function to clone and build uhubctl
build_uhubctl() {
    print_info "Cloning uhubctl repository..."
    
    # Remove existing directory if it exists
    if [ -d "uhubctl" ]; then
        print_warning "Removing existing uhubctl directory..."
        rm -rf uhubctl
    fi
    
    git clone https://github.com/mvp/uhubctl.git
    cd uhubctl
    
    # Checkout specific version if not master
    if [ "$VERSION" != "master" ]; then
        print_info "Checking out version $VERSION..."
        git checkout "$VERSION"
    fi
    
    print_info "Building uhubctl..."
    make
    
    print_info "Installing uhubctl..."
    sudo make install
    
    print_success "uhubctl built and installed"
}

# Function to setup udev rules
setup_udev_rules() {
    print_info "Setting up udev rules for USB permissions..."
    
    UDEV_RULES_FILE="/etc/udev/rules.d/52-usb.rules"
    
    # Create udev rules content
    cat << EOF | sudo tee "$UDEV_RULES_FILE" > /dev/null
# uhubctl – USB hub per-port power control https://github.com/mvp/uhubctl
#
# This file can be distributed under the terms and conditions of the
# GNU General Public License version 2.

# uhubctl udev rules for rootless operation on Linux for users in group 'dialout'.
#
# Generated by uhubctl installation script for idVendor: $IDVENDOR

# This is for Linux before 6.0:
SUBSYSTEM=="usb", DRIVER=="hub|usb", MODE="0664", GROUP="dialout", ATTR{idVendor}=="$IDVENDOR"

# This is for Linux 6.0 or later (ok to keep this block present for older Linux kernels):
SUBSYSTEM=="usb", DRIVER=="hub|usb", ATTR{idVendor}=="$IDVENDOR", \\
  RUN+="/bin/sh -c \"chown -f root:dialout \$sys\$devpath/*port*/disable || true\"" \\
  RUN+="/bin/sh -c \"chmod -f 660 \$sys\$devpath/*port*/disable || true\""
EOF

    print_success "Udev rules created at $UDEV_RULES_FILE"
}

# Function to add user to dialout group
setup_user_permissions() {
    print_info "Adding current user ($USER) to dialout group..."
    sudo usermod -a -G dialout "$USER"
    print_success "User added to dialout group"
}

# Function to reload udev rules
reload_udev_rules() {
    print_info "Reloading udev rules..."
    sudo udevadm trigger --attr-match=subsystem=usb
    print_success "Udev rules reloaded"
}

# Function to verify installation
verify_installation() {
    print_info "Verifying uhubctl installation..."
    
    if command_exists uhubctl; then
        INSTALLED_VERSION=$(uhubctl --version 2>/dev/null | head -n1 || echo "Unknown version")
        print_success "uhubctl is installed: $INSTALLED_VERSION"
    else
        print_error "uhubctl installation verification failed"
        exit 1
    fi
}

# Function to display post-installation instructions
show_post_install_info() {
    print_info "Installation completed successfully!"
    print_warning "IMPORTANT: You need to log out and log back in (or reboot) for group changes to take effect."
    echo
    print_info "After logging back in, you can test uhubctl with:"
    echo "  uhubctl"
    echo
    print_info "To control USB ports without sudo:"
    echo "  uhubctl -a off -p 2    # Turn off port 2"
    echo "  uhubctl -a on -p 2     # Turn on port 2"
    echo
    print_info "If you have multiple USB hubs, first list them:"
    echo "  uhubctl"
    echo "Then specify the hub location:"
    echo "  uhubctl -l 1-1 -a off -p 2"
    echo
    print_warning "Be careful not to turn off ports connected to your keyboard or mouse!"
}

# Main script execution
main() {
    print_info "uhubctl Installation Script"
    print_info "============================"
    
    check_not_root
    validate_arguments "$@"
    
    print_info "Starting installation process..."
    
    install_dependencies
    build_uhubctl
    setup_udev_rules
    setup_user_permissions
    reload_udev_rules
    verify_installation
    
    # Clean up
    cd ..
    rm -rf uhubctl
    
    show_post_install_info
}

# Run main function with all arguments
main "$@"
